### ISSUE TITLE
Iterate over all values

### ISSUE THREAD

**Issue by alxhotel** [most-inesctec/I2Bplus-tree#6]
Is there a way to iterate over all values of the tree?

cc @EdgarACarneiro

**Comment by EdgarACarneiro** [comment]
Hey @alxhotel 

Currently, there isn't a way to iterate over all values stored in the tree. However, if you know the full extent of the values you can run a `tree.allRangeSearch(lowestValue, highestValue)` and that will get you all the values in the tree.

**Comment by Nikovic** [comment]
If I'm not mistaken, that means `tree.allRangeSearch(Number.NEGATIVE_INFINITY, Number.POSITIVE_INFINITY)` already gives you a (slightly unfortunate, but working) way to iterate over all values in the tree, right?

**Comment by EdgarACarneiro** [comment]
Yes, that should be true @Nikovic
